Renamed PKI_8_0_RTM_BRANCH to PKI_8_BRANCH.

diff --git a/pki/base/ca/shared/etc/init.d/httpd b/pki/base/ca/shared/etc/init.d/httpd
--- a/pki/base/ca/shared/etc/init.d/httpd
+++ b/pki/base/ca/shared/etc/init.d/httpd
@@ -26,6 +26,7 @@
 # processname:  [PKI_INSTANCE_ID]
 # pidfile:      /var/run/[PKI_INSTANCE_ID].pid
 # config:       [PKI_INSTANCE_PATH]/conf/tomcat5.conf
+# wdpidfile:    [PKI_INSTANCE_PATH]/logs/wd-[PKI_INSTANCE_ID].pid
 #
 # Gomez Henri <hgomez@users.sourceforge.net>
 # Keith Irwin <keith_irwin@non.hp.com>
@@ -71,17 +72,25 @@ if [ $? -ne 0 ] ; then
 	exit 255
 fi
 
+# Check to insure that at least one PKI subsystem
+# currently resides on this system.
+if	[ ! -x /usr/bin/pkiarch   ] ||
+	[ ! -x /usr/bin/pkiflavor ] ||
+	[ ! -x /usr/bin/pkiname   ]; then
+	echo "This machine is missing all PKI subsystems!"
+	exit 255
+fi
+
 # Check to insure that this script's associated PKI
 # subsystem currently resides on this system.
 PKI_SUBSYSTEM_TYPE=[PKI_SUBSYSTEM_TYPE]
-if [ ! -d /usr/share/pki/${PKI_SUBSYSTEM_TYPE} ] ; then
+if [ ! -d /usr/share/`pkiflavor`/${PKI_SUBSYSTEM_TYPE} ] ; then
 	echo "This machine is missing the '${PKI_SUBSYSTEM_TYPE}' subsystem!"
 	exit 255
 fi
 
 # Obtain the operating system upon which this script is being executed
-OS=`uname -s`
-ARCHITECTURE=""
+OS=`pkiname`
 
 # This script must be run as root!
 RV=0
@@ -90,16 +99,10 @@ if [ ${OS} = "Linux" ] ; then
 		echo "Must be 'root' to execute '$0'!"
 		exit 1
 	fi
-	ARCHITECTURE=`uname -i`
 elif [ ${OS} = "SunOS" ] ; then
 	if [ `/usr/xpg4/bin/id -u` -ne 0 ] ; then
 		echo "Must be 'root' to execute '$0'!"
 		exit 1
-	fi
-	ARCHITECTURE=`uname -p`
-	if	[ "${ARCHITECTURE}" = "sparc" ] &&
-		[ -d "/usr/lib/sparcv9/" ] ; then
-		ARCHITECTURE="sparcv9"
 	fi
 else
 	echo "Unsupported OS '${OS}'!"
@@ -205,6 +208,7 @@ fi
 # file instead ; it will be read by the $tomcat script
 
 pidfile=${PIDFILE:-/var/run/[PKI_INSTANCE_ID].pid}
+wdpidfile=${NUXWDOG_PIDFILE:-[PKI_INSTANCE_PATH]/logs/wd-[PKI_INSTANCE_ID].pid}
 lockfile=${LOCKFILE:-/var/lock/subsys/[PKI_INSTANCE_ID]}
 pki_instance_configuration_file=[PKI_INSTANCE_PATH]/conf/CS.cfg
 RESTART_SERVER=[PKI_INSTANCE_PATH]/conf/restart_server_after_configuration
@@ -566,6 +570,9 @@ start()
 	chown $TOMCAT_USER:$TOMCAT_GROUP $CATALINA_PID
   	[ -x /sbin/restorecon ] && /sbin/restorecon  $CATALINA_PID
 
+        NUXWDOG_PID=${wdpidfile}
+        export NUXWDOG_PID
+
         # restore context for ncipher hsm
         [ -x /sbin/restorecon ] && [ -d /dev/nfast ] && /sbin/restorecon -R /dev/nfast
 
@@ -637,26 +644,26 @@ start()
 		CLASSPATH="$CLASSPATH":/usr/share/java/avalon-logkit.jar
 		CLASSPATH="$CLASSPATH":/usr/share/java/cmsutil.jar
 		CLASSPATH="$CLASSPATH":/usr/share/java/commons-logging.jar
-		if [ "$ARCHITECTURE" = "sparc" ] ; then
+		if [ `pkiarch` = "sparc" ] ; then
 			CLASSPATH="$CLASSPATH":/usr/lib/java/dirsec/jss4.jar
-		elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-			CLASSPATH="$CLASSPATH":/usr/lib/sparcv9/java/dirsec/jss4.jar
+		elif [ `pkiarch` = "sparcv9" ] ; then
+			CLASSPATH="$CLASSPATH":/usr/lib/`pkiarch`/java/dirsec/jss4.jar
 		fi
 		CLASSPATH="$CLASSPATH":/usr/share/java/ldapjdk.jar
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/common/lib/naming-factory.jar
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/common/lib/naming-resources.jar
-		CLASSPATH="$CLASSPATH":/usr/share/java/pki/nsutil.jar
-		if [ "$ARCHITECTURE" = "sparc" ] ; then
+		CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/nsutil.jar
+		if [ `pkiarch` = "sparc" ] ; then
 			CLASSPATH="$CLASSPATH":/usr/lib/java/osutil.jar
-		elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-			CLASSPATH="$CLASSPATH":/usr/lib/sparcv9/java/osutil.jar
+		elif [ `pkiarch` = "sparcv9" ] ; then
+			CLASSPATH="$CLASSPATH":/usr/lib/`pkiarch`/java/osutil.jar
 		fi
 		CLASSPATH="$CLASSPATH":/usr/share/java/rhino.jar
 		CLASSPATH="$CLASSPATH":/usr/share/java/servletapi5.jar
-		if [ "$ARCHITECTURE" = "sparc" ] ; then
+		if [ `pkiarch` = "sparc" ] ; then
 			CLASSPATH="$CLASSPATH":/usr/lib/java/symkey.jar
-		elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-			CLASSPATH="$CLASSPATH":/usr/lib/sparcv9/java/symkey.jar
+		elif [ `pkiarch` = "sparcv9" ] ; then
+			CLASSPATH="$CLASSPATH":/usr/lib/`pkiarch`/java/symkey.jar
 		fi
 		CLASSPATH="$CLASSPATH":/usr/share/java/velocity.jar
 		CLASSPATH="$CLASSPATH":/usr/share/java/xalan-j2.jar
@@ -845,10 +852,10 @@ start()
 		### END LINUX-SPECIFIC FILE BUT SOLARIS-SPECIFIC LINK
 
 		### if [ ! -e /var/lib/tomcat5/common/lib/jss4.jar ]; then
-		###     if [ "$ARCHITECTURE" = "sparc" ] ; then
+		###     if [ `pkiarch` = "sparc" ] ; then
 		###         ln -s /usr/lib/java/dirsec/jss4.jar jss4.jar
-		###     elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-		###         ln -s /usr/lib/sparcv9/java/dirsec/jss4.jar jss4.jar
+		###     elif [ `pkiarch` = "sparcv9" ] ; then
+		###         ln -s /usr/lib/`pkiarch`/java/dirsec/jss4.jar jss4.jar
 		###     fi
 		### fi
 		### if [ ! -e /var/lib/tomcat5/common/lib/ldapjdk.jar ]; then
@@ -859,13 +866,13 @@ start()
 		### naming-resources.jar
 
 		### if [ ! -e /var/lib/tomcat5/common/lib/nsutil.jar ]; then
-		###     ln -s /usr/share/java/pki/nsutil.jar nsutil.jar
+		###     ln -s /usr/share/java/`pkiflavor`/nsutil.jar nsutil.jar
 		### fi
 		### if [ ! -e /var/lib/tomcat5/common/lib/osutil.jar ]; then
-		###     if [ "$ARCHITECTURE" = "sparc" ] ; then
+		###     if [ `pkiarch` = "sparc" ] ; then
 		###         ln -s /usr/lib/java/osutil.jar osutil.jar
-		###     elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-		###         ln -s /usr/lib/sparcv9/java/osutil.jar osutil.jar
+		###     elif [ `pkiarch` = "sparcv9" ] ; then
+		###         ln -s /usr/lib/`pkiarch`/java/osutil.jar osutil.jar
 		###     fi
 		### fi
 		### if [ ! -e /var/lib/tomcat5/common/lib/rhino.jar ]; then
@@ -879,10 +886,10 @@ start()
 		### END SOLARIS-SPECIFIC LINKS
 
 		### if [ ! -e /var/lib/tomcat5/common/lib/symkey.jar ]; then
-		###     if [ "$ARCHITECTURE" = "sparc" ] ; then
+		###     if [ `pkiarch` = "sparc" ] ; then
 		###         ln -s /usr/lib/java/symkey.jar symkey.jar
-		###     elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-		###         ln -s /usr/lib/sparcv9/java/symkey.jar symkey.jar
+		###     elif [ `pkiarch` = "sparcv9" ] ; then
+		###         ln -s /usr/lib/`pkiarch`/java/symkey.jar symkey.jar
 		###     fi
 		### fi
 		### if [ ! -e /var/lib/tomcat5/common/lib/velocity.jar ]; then
@@ -957,10 +964,10 @@ start()
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/server/lib/catalina-optional.jar
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/server/lib/catalina-storeconfig.jar
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/server/lib/catalina.jar
-		if [ "$ARCHITECTURE" = "sparc" ] ; then
+		if [ `pkiarch` = "sparc" ] ; then
 			CLASSPATH="$CLASSPATH":/usr/lib/java/dirsec/jss4.jar
-		elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-			CLASSPATH="$CLASSPATH":/usr/lib/sparcv9/java/dirsec/jss4.jar
+		elif [ `pkiarch` = "sparcv9" ] ; then
+			CLASSPATH="$CLASSPATH":/usr/lib/`pkiarch`/java/dirsec/jss4.jar
 		fi
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/server/lib/servlets-cgi.renametojar
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/server/lib/servlets-default.jar
@@ -1020,10 +1027,10 @@ start()
 		### catalina-storeconfig.jar
 		### catalina.jar
 		### if [ ! -e /var/lib/tomcat5/server/lib/jss4.jar ]; then
-		###     if [ "$ARCHITECTURE" = "sparc" ] ; then
+		###     if [ `pkiarch` = "sparc" ] ; then
 		###         ln -s /usr/lib/java/dirsec/jss4.jar jss4.jar
-		###     elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-		###         ln -s /usr/lib/sparcv9/java/dirsec/jss4.jar jss4.jar
+		###     elif [ `pkiarch` = "sparcv9" ] ; then
+		###         ln -s /usr/lib/`pkiarch`/java/dirsec/jss4.jar jss4.jar
 		###     fi
 		### fi
 		### servlets-cgi.renametojar
@@ -1057,7 +1064,7 @@ start()
 	if [ ${OS} = "SunOS" ] ; then
 		su  $TOMCAT_USER -c "$TOMCAT_SCRIPT start" > /dev/null
         else
-		runuser -s /bin/bash $TOMCAT_USER -c "$TOMCAT_SCRIPT start" > /dev/null
+		runuser -s /bin/bash $TOMCAT_USER -c "$TOMCAT_SCRIPT start" 
 	fi
 
 	RETVAL=$?
diff --git a/pki/base/tks/shared/conf/dtomcat5 b/pki/base/tks/shared/conf/dtomcat5
--- a/pki/base/tks/shared/conf/dtomcat5
+++ b/pki/base/tks/shared/conf/dtomcat5
@@ -45,6 +45,8 @@
 #   CATALINA_PID    (Optional) Path of the file which should contains the pid
 #                   of catalina startup java process, when start (fork) is used
 #
+#   NUXWDOG_PID      (Optional) Path of the file which should contain the pid
+#                   of the nuxwdog watchdog process used to start the server
 # $Id: catalina.sh,v 1.19 2005/03/03 15:13:39 remm Exp $
 # -----------------------------------------------------------------------------
 
@@ -59,16 +61,25 @@ if [ $? -ne 0 ] ; then
 	exit 255
 fi
 
+# Check to insure that at least one PKI subsystem
+# currently resides on this system.
+if	[ ! -x /usr/bin/pkiarch   ] ||
+	[ ! -x /usr/bin/pkiflavor ] ||
+	[ ! -x /usr/bin/pkiname   ]; then
+	echo "This machine is missing all PKI subsystems!"
+	exit 255
+fi
+
 # Check to insure that this script's associated PKI
 # subsystem currently resides on this system.
 PKI_SUBSYSTEM_TYPE=[PKI_SUBSYSTEM_TYPE]
-if [ ! -d /usr/share/pki/${PKI_SUBSYSTEM_TYPE} ] ; then
+if [ ! -d /usr/share/`pkiflavor`/${PKI_SUBSYSTEM_TYPE} ] ; then
 	echo "This machine is missing the '${PKI_SUBSYSTEM_TYPE}' subsystem!"
 	exit 255
 fi
 
 # OS specific support.  $var _must_ be set to either true or false.
-OS=`uname -s`
+OS=`pkiname`
 cygwin=false
 os400=false
 case "${OS}" in
@@ -212,6 +223,7 @@ fi
 
 if [ ${OS} = "Linux" ] ; then
 	CLASSPATH="$CLASSPATH":"$CATALINA_HOME"/bin/bootstrap.jar:"$CATALINA_HOME"/bin/commons-logging-api.jar:`/usr/bin/build-classpath mx4j/mx4j-impl`:`/usr/bin/build-classpath mx4j/mx4j-jmx`
+        CLASSPATH="$CLASSPATH":"$CATALINA_HOME"/common/lib/nuxwdog.jar
 elif [ ${OS} = "SunOS" ] ; then
 	# The following definitions are provided for Solaris
 	# platforms since they are unable to execute the
@@ -222,32 +234,32 @@ elif [ ${OS} = "SunOS" ] ; then
 	CLASSPATH="$CLASSPATH":"$CATALINA_HOME"/bin/commons-logging-api.jar
 	CLASSPATH="$CLASSPATH":/usr/share/java/mx4j/mx4j-impl.jar
 	CLASSPATH="$CLASSPATH":/usr/share/java/mx4j/mx4j-jmx.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/base.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/certsrv.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/cms.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/cms72.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/cms72_en.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/cmsbundle.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/cmscore.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/cmsutil.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/cstools.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/mcc70.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/mcc70_en.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/nmclf70.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/nmclf70_en.jar
-	CLASSPATH="$CLASSPATH":/usr/share/java/pki/nsutil.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/base.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/certsrv.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/cms.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/cms72.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/cms72_en.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/cmsbundle.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/cmscore.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/cmsutil.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/cstools.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/mcc70.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/mcc70_en.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/nmclf70.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/nmclf70_en.jar
+	CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/nsutil.jar
 
-	if [ -d /usr/share/java/pki/ca ]; then
-		CLASSPATH="$CLASSPATH":/usr/share/java/pki/ca/ca.jar
+	if [ -d /usr/share/java/`pkiflavor`/ca ]; then
+		CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/ca/ca.jar
 	fi
-	if [ -d /usr/share/java/pki/kra ]; then
-		CLASSPATH="$CLASSPATH":/usr/share/java/pki/kra/kra.jar
+	if [ -d /usr/share/java/`pkiflavor`/kra ]; then
+		CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/kra/kra.jar
 	fi
-	if [ -d /usr/share/java/pki/ocsp ]; then
-		CLASSPATH="$CLASSPATH":/usr/share/java/pki/ocsp/ocsp.jar
+	if [ -d /usr/share/java/`pkiflavor`/ocsp ]; then
+		CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/ocsp/ocsp.jar
 	fi
-	if [ -d /usr/share/java/pki/tks ]; then
-		CLASSPATH="$CLASSPATH":/usr/share/java/pki/tks/tks.jar
+	if [ -d /usr/share/java/`pkiflavor`/tks ]; then
+		CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/tks/tks.jar
 	fi
 fi
 
@@ -264,6 +276,10 @@ if [ -z "$CATALINA_PID" ] ; then
     export CATALINA_PID=/var/run/tomcat5.pid
 fi
 
+if [ -z "$NUXWDOG_PID" ] ; then
+    export NUXWDOG_PID=[PKI_INSTANCE_PATH]/logs/wd-[PKI_INSTANCE_ID].pid
+fi
+
 # For Cygwin, switch paths to Windows format before running java
 if $cygwin; then
   JAVA_HOME=`cygpath --absolute --windows "$JAVA_HOME"`
@@ -277,15 +293,16 @@ if $cygwin; then
 fi
 
 # ----- Execute The Requested Command -----------------------------------------
-echo "Using CATALINA_PID $CATALINA_PID"
-echo "Using CATALINA_BASE:   $CATALINA_BASE"
-echo "Using CATALINA_HOME:   $CATALINA_HOME"
-echo "Using CATALINA_TMPDIR: $CATALINA_TMPDIR"
-if [ "$1" = "debug" -o "$1" = "javac" ] ; then
-  echo "Using JAVA_HOME:       $JAVA_HOME"
-else
-  echo "Using JRE_HOME:       $JRE_HOME"
-fi
+#echo "Using CATALINA_PID $CATALINA_PID"
+#echo "Using NUXWDOG_PID: $NUXWDOG_PID"
+#echo "Using CATALINA_BASE:   $CATALINA_BASE"
+#echo "Using CATALINA_HOME:   $CATALINA_HOME"
+#echo "Using CATALINA_TMPDIR: $CATALINA_TMPDIR"
+#if [ "$1" = "debug" -o "$1" = "javac" ] ; then
+#  echo "Using JAVA_HOME:       $JAVA_HOME"
+#else
+#  echo "Using JRE_HOME:       $JRE_HOME"
+#fi
 
 if [ "$1" = "jpda" ] ; then
   if [ -z "$JPDA_TRANSPORT" ]; then
@@ -310,23 +327,27 @@ if [ "$1" = "debug" ] ; then
     if [ "$1" = "-security" ] ; then
       echo "Using Security Manager"
       shift
-      exec "$_RUNJDB" $JAVA_OPTS $CATALINA_OPTS \
-        -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" -classpath "$CLASSPATH" \
-        -sourcepath "$CATALINA_HOME"/../../jakarta-tomcat-catalina/catalina/src/share \
-        -Djava.security.manager \
-        -Djava.security.policy=="$CATALINA_BASE"/conf/catalina.policy \
-        -Dcatalina.base="$CATALINA_BASE" \
-        -Dcatalina.home="$CATALINA_HOME" \
-        -Djava.io.tmpdir="$CATALINA_TMPDIR" \
-        org.apache.catalina.startup.Bootstrap "$@" start
+      FNAME="$CATALINA_BASE"/conf/nuxwdog-secdebug.conf
+      if [ ! -f $FNAME ]; then
+        echo "ExeFile $_RUNJDB" > $FNAME
+        echo "ExeArgs $_RUNJDB $JAVA_OPTS $CATALINA_OPTS -Djava.endorsed.dirs=$JAVA_ENDORSED_DIRS -classpath $CLASSPATH -sourcepath "$CATALINA_HOME"/../../jakarta-tomcat-catalina/catalina/src/share -Djava.security.manager -Djava.security.policy=="$CATALINA_BASE"/conf/catalina.policy -Dcatalina.base=$CATALINA_BASE -Dcatalina.home=$CATALINA_HOME -Djava.io.tmpdir=$CATALINA_TMPDIR org.apache.catalina.startup.Bootstrap $@ start" >> $FNAME
+        echo "TmpDir ${CATALINA_BASE}/logs/pids" >> $FNAME
+        echo "ChildSecurity 1" >> $FNAME
+        echo "PidFile $NUXWDOG_PID" >> $FNAME
+        echo "ChildPidFile $CATALINA_PID" >> $FNAME
+      fi
+      /usr/bin/nuxwdog -f $FNAME
     else
-      exec "$_RUNJDB" $JAVA_OPTS $CATALINA_OPTS \
-        -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" -classpath "$CLASSPATH" \
-        -sourcepath "$CATALINA_HOME"/../../jakarta-tomcat-catalina/catalina/src/share \
-        -Dcatalina.base="$CATALINA_BASE" \
-        -Dcatalina.home="$CATALINA_HOME" \
-        -Djava.io.tmpdir="$CATALINA_TMPDIR" \
-        org.apache.catalina.startup.Bootstrap "$@" start
+      FNAME="$CATALINA_BASE"/conf/nuxwdog-debug.conf
+      if [ ! -f $FNAME ]; then
+        echo "ExeFile $_RUNJDB" > $FNAME
+        echo "ExeArgs $_RUNJDB $JAVA_OPTS $CATALINA_OPTS -Djava.endorsed.dirs=$JAVA_ENDORSED_DIRS -classpath $CLASSPATH -sourcepath "$CATALINA_HOME"/../../jakarta-tomcat-catalina/catalina/src/share -Dcatalina.base=$CATALINA_BASE -Dcatalina.home=$CATALINA_HOME -Djava.io.tmpdir=$CATALINA_TMPDIR org.apache.catalina.startup.Bootstrap $@ start" >> $FNAME
+        echo "TmpDir ${CATALINA_BASE}/logs/pids" >> $FNAME
+        echo "ChildSecurity 1" >> $FNAME
+        echo "PidFile $NUXWDOG_PID" >> $FNAME
+        echo "ChildPidFile $CATALINA_PID" >> $FNAME
+      fi
+      /usr/bin/nuxwdog -f $FNAME
     fi
   fi
 
@@ -336,21 +357,27 @@ elif [ "$1" = "run" ]; then
   if [ "$1" = "-security" ] ; then
     echo "Using Security Manager"
     shift
-    exec "$_RUNJAVA" $JAVA_OPTS $CATALINA_OPTS \
-      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" -classpath "$CLASSPATH" \
-      -Djava.security.manager \
-      -Djava.security.policy=="$CATALINA_BASE"/conf/catalina.policy \
-      -Dcatalina.base="$CATALINA_BASE" \
-      -Dcatalina.home="$CATALINA_HOME" \
-      -Djava.io.tmpdir="$CATALINA_TMPDIR" \
-      org.apache.catalina.startup.Bootstrap "$@" start
+    FNAME="$CATALINA_BASE"/conf/nuxwdog-secrun.conf
+    if [ ! -f $FNAME ]; then
+      echo "ExeFile $_RUNJAVA" > $FNAME
+      echo "ExeArgs $_RUNJAVA $JAVA_OPTS $CATALINA_OPTS -Djava.endorsed.dirs=$JAVA_ENDORSED_DIRS -classpath $CLASSPATH -Djava.security.manager -Djava.security.policy=="$CATALINA_BASE"/conf/catalina.policy -Dcatalina.base=$CATALINA_BASE -Dcatalina.home=$CATALINA_HOME -Djava.io.tmpdir=$CATALINA_TMPDIR org.apache.catalina.startup.Bootstrap $@ start" >> $FNAME
+      echo "TmpDir ${CATALINA_BASE}/logs/pids" >> $FNAME
+      echo "ChildSecurity 1" >> $FNAME
+      echo "PidFile $NUXWDOG_PID" >> $FNAME
+      echo "ChildPidFile $CATALINA_PID" >> $FNAME
+    fi
+    /usr/bin/nuxwdog -f $FNAME
   else
-    exec "$_RUNJAVA" $JAVA_OPTS $CATALINA_OPTS \
-      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" -classpath "$CLASSPATH" \
-      -Dcatalina.base="$CATALINA_BASE" \
-      -Dcatalina.home="$CATALINA_HOME" \
-      -Djava.io.tmpdir="$CATALINA_TMPDIR" \
-      org.apache.catalina.startup.Bootstrap "$@" start
+    FNAME="$CATALINA_BASE"/conf/nuxwdog-run.conf
+    if [ ! -f $FNAME ]; then
+      echo "ExeFile $_RUNJAVA" > $FNAME
+      echo "ExeArgs $_RUNJAVA $JAVA_OPTS $CATALINA_OPTS -Djava.endorsed.dirs=$JAVA_ENDORSED_DIRS -classpath $CLASSPATH -Dcatalina.base=$CATALINA_BASE -Dcatalina.home=$CATALINA_HOME -Djava.io.tmpdir=$CATALINA_TMPDIR org.apache.catalina.startup.Bootstrap $@ start" >> $FNAME
+      echo "TmpDir ${CATALINA_BASE}/logs/pids" >> $FNAME
+      echo "ChildSecurity 1" >> $FNAME
+      echo "PidFile $NUXWDOG_PID" >> $FNAME
+      echo "ChildPidFile $CATALINA_PID" >> $FNAME
+    fi
+    /usr/bin/nuxwdog -f $FNAME
   fi
 
 elif [ "$1" = "start" ] ; then
@@ -360,31 +387,34 @@ elif [ "$1" = "start" ] ; then
   if [ "$1" = "-security" ] ; then
     echo "Using Security Manager"
     shift
-    "$_RUNJAVA" $JAVA_OPTS $CATALINA_OPTS \
-      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" -classpath "$CLASSPATH" \
-      -Djava.security.manager \
-      -Djava.security.policy=="$CATALINA_BASE"/conf/catalina.policy \
-      -Dcatalina.base="$CATALINA_BASE" \
-      -Dcatalina.home="$CATALINA_HOME" \
-      -Djava.io.tmpdir="$CATALINA_TMPDIR" \
-      org.apache.catalina.startup.Bootstrap "$@" start \
-      >> "$CATALINA_BASE"/logs/catalina.out 2>&1 &
+    FNAME="$CATALINA_BASE"/conf/nuxwdog-secstart.conf
+    if [ ! -f $FNAME ]; then
+      echo "ExeFile $_RUNJAVA" > $FNAME
+      echo "ExeArgs $_RUNJAVA $JAVA_OPTS $CATALINA_OPTS -Djava.endorsed.dirs=$JAVA_ENDORSED_DIRS -classpath $CLASSPATH -Djava.security.manager -Djava.security.policy=="$CATALINA_BASE"/conf/catalina.policy -Dcatalina.base=$CATALINA_BASE -Dcatalina.home=$CATALINA_HOME -Djava.io.tmpdir=$CATALINA_TMPDIR org.apache.catalina.startup.Bootstrap $@ start" >> $FNAME
+      echo "TmpDir ${CATALINA_BASE}/logs/pids" >> $FNAME
+      echo "ChildSecurity 1" >> $FNAME
+      echo "ExeOut ${CATALINA_BASE}/logs/catalina.out" >> $FNAME
+      echo "ExeErr ${CATALINA_BASE}/logs/catalina.out" >> $FNAME
+      echo "ExeBackground 1" >> $FNAME
+      echo "PidFile $NUXWDOG_PID" >> $FNAME
+      echo "ChildPidFile $CATALINA_PID" >> $FNAME
+    fi
+    /usr/bin/nuxwdog -f $FNAME
 
-      if [ ! -z "$CATALINA_PID" ]; then
-        echo $! > $CATALINA_PID
-      fi
   else
-    "$_RUNJAVA" $JAVA_OPTS $CATALINA_OPTS \
-      -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" -classpath "$CLASSPATH" \
-      -Dcatalina.base="$CATALINA_BASE" \
-      -Dcatalina.home="$CATALINA_HOME" \
-      -Djava.io.tmpdir="$CATALINA_TMPDIR" \
-      org.apache.catalina.startup.Bootstrap "$@" start \
-      >> "$CATALINA_BASE"/logs/catalina.out 2>&1 &
-
-      if [ ! -z "$CATALINA_PID" ]; then
-        echo $! > $CATALINA_PID
-      fi
+    FNAME="$CATALINA_BASE"/conf/nuxwdog-start.conf
+    if [ ! -f $FNAME ]; then
+      echo "ExeFile $_RUNJAVA" > $FNAME
+      echo "ExeArgs $_RUNJAVA $JAVA_OPTS $CATALINA_OPTS -Djava.endorsed.dirs=$JAVA_ENDORSED_DIRS -classpath $CLASSPATH -Dcatalina.base=$CATALINA_BASE -Dcatalina.home=$CATALINA_HOME -Djava.io.tmpdir=$CATALINA_TMPDIR org.apache.catalina.startup.Bootstrap $@ start" >> $FNAME
+      echo "TmpDir ${CATALINA_BASE}/logs/pids" >> $FNAME
+      echo "ChildSecurity 1" >> $FNAME
+      echo "ExeOut ${CATALINA_BASE}/logs/catalina.out" >> $FNAME
+      echo "ExeErr ${CATALINA_BASE}/logs/catalina.out" >> $FNAME
+      echo "ExeBackground 1" >> $FNAME
+      echo "PidFile $NUXWDOG_PID" >> $FNAME
+      echo "ChildPidFile $CATALINA_PID" >> $FNAME
+    fi
+    /usr/bin/nuxwdog -f $FNAME
   fi
 
 elif [ "$1" = "stop" ] ; then
@@ -396,12 +426,8 @@ elif [ "$1" = "stop" ] ; then
     FORCE=1
   fi
 
-  "$_RUNJAVA" $JAVA_OPTS $CATALINA_OPTS \
-    -Djava.endorsed.dirs="$JAVA_ENDORSED_DIRS" -classpath "$CLASSPATH" \
-    -Dcatalina.base="$CATALINA_BASE" \
-    -Dcatalina.home="$CATALINA_HOME" \
-    -Djava.io.tmpdir="$CATALINA_TMPDIR" \
-    org.apache.catalina.startup.Bootstrap "$@" stop
+  # stop by sending SIGTERM to nuxwdog
+  kill `cat $NUXWDOG_PID`
 
   if [ $FORCE -eq 1 ]; then
     if [ ! -z "$CATALINA_PID" ]; then
diff --git a/pki/base/tps/etc/init.d/httpd b/pki/base/tps/etc/init.d/httpd
--- a/pki/base/tps/etc/init.d/httpd
+++ b/pki/base/tps/etc/init.d/httpd
@@ -29,6 +29,9 @@
 # processname:  [INSTANCE_ID]
 # config:       [HTTPD_CONF]
 # pidfile:      [SERVER_ROOT]/logs/[INSTANCE_ID].pid
+# wdpidfile:    [SERVER_ROOT]/logs/wd-[INSTANCE_ID].pid
+# wdconfig:     [SERVER_ROOT]/conf/nuxwdog-start.conf
+# wdtempdir:    [SERVER_ROOT]/logs/pids
 
 # Disallow 'others' the ability to 'write' to new files
 umask 00002
@@ -41,17 +44,26 @@ if [ $? -ne 0 ] ; then
 	exit 255
 fi
 
+# Check to insure that at least one PKI subsystem
+# currently resides on this system.
+if	[ ! -x /usr/bin/pkiarch   ] ||
+	[ ! -x /usr/bin/pkiflavor ] ||
+	[ ! -x /usr/bin/pkiname   ]; then
+	echo "This machine is missing all PKI subsystems!"
+	exit 255
+fi
+
 # Check to insure that this script's associated PKI
 # subsystem currently resides on this system.
 SUBSYSTEM_TYPE=[SUBSYSTEM_TYPE]
-if [ ! -d /usr/share/pki/${SUBSYSTEM_TYPE} ] ; then
+if [ ! -d /usr/share/`pkiflavor`/${SUBSYSTEM_TYPE} ] ; then
 	echo "This machine is missing the '${SUBSYSTEM_TYPE}' subsystem!"
 	exit 255
 fi
 
 # Obtain the operating system upon which this script is being executed
-OS=`uname -s`
-ARCHITECTURE=""
+OS=`pkiname`
+ARCHITECTURE=`pkiarch`
 
 # Time to wait in seconds, before killing process
 #
@@ -67,16 +79,10 @@ if [ ${OS} = "Linux" ] ; then
 		echo "Must be 'root' to execute '$0'!"
 		exit 1
 	fi
-	ARCHITECTURE=`uname -i`
 elif [ ${OS} = "SunOS" ] ; then
 	if [ `/usr/xpg4/bin/id -u` -ne 0 ] ; then
 		echo "Must be 'root' to execute '$0'!"
 		exit 1
-	fi
-	ARCHITECTURE=`uname -p`
-	if	[ "${ARCHITECTURE}" = "sparc" ] &&
-		[ -d "/usr/lib/sparcv9/" ] ; then
-		ARCHITECTURE="sparcv9"
 	fi
 else
 	echo "Unsupported OS '${OS}'!"
@@ -161,6 +167,9 @@ prog=[INSTANCE_ID]
 pki_instance_configuration_file=[SERVER_ROOT]/conf/CS.cfg
 pidfile=${PIDFILE:-[SERVER_ROOT]/logs/[INSTANCE_ID].pid}
 lockfile=${LOCKFILE:-/var/lock/subsys/[INSTANCE_ID]}
+wdpidfile=${WDPIDFILE:-[SERVER_ROOT]/logs/wd-[INSTANCE_ID].pid}
+wdtempdir=${WDTEMPDIR:-[SERVER_ROOT]/logs/pids}
+wdconfig=${WDCONFIG:-[SERVER_ROOT]/conf/nuxwdog-start.conf}
 RESTART_SERVER=[SERVER_ROOT]/conf/restart_server_after_configuration
 RETVAL=0
 
@@ -512,6 +521,15 @@ start()
 		rm -f ${RESTART_SERVER}
 	fi
 
+        if [ -f ${wdpidfile} ]; then
+            read kpid < ${wdpidfile}
+            if checkpid $kpid 2>&1; then
+                echo
+                echo "Watchdog process already running. If the server is not operational, please use restart to stop and start the server."
+                return 255
+            fi
+        fi
+
 	if [ -f ${lockfile} ] ; then
 		if [ -f ${pidfile} ]; then
 			read kpid < ${pidfile}
@@ -532,27 +550,29 @@ start()
         # restore context for ncipher hsm
         [ -x /sbin/restorecon ] && [ -d /dev/nfast ] && /sbin/restorecon -R /dev/nfast
 
-	if [ -f /etc/init.d/functions ]; then
-		/usr/sbin/selinuxenabled
-		RETVAL=$?
-		if [ $RETVAL = 0 ] ; then	
-			if [ ${ARCHITECTURE} = "i386" ] ; then
-				LANG=$HTTPD_LANG daemon runcon -t pki_tps_t -- $httpd $OPTIONS
-				# overwrite output from "daemon"
-				echo -n $"Starting $prog:                                        "
-			elif [ ${ARCHITECTURE} = "x86_64" ] ; then
-				# NOTE:  "daemon" is incompatible with "httpd"
-				#        on 64-bit architectures
-				LANG=$HTTPD_LANG runcon -t pki_tps_t -- $httpd $OPTIONS
-			fi
-		else
-			LANG=$HTTPD_LANG daemon $httpd $OPTIONS
-			# overwrite output from "daemon"
-			echo -n $"Starting $prog:                                        "
-		fi
-	else
-		LANG=$HTTPD_LANG $httpd $OPTIONS -k start
-	fi
+        # re-create config file
+        if [ -f $wdconfig ]; then
+            rm -f $wdconfig
+        fi
+ 
+        echo "ExeFile $httpd" > $wdconfig
+        echo "ExeArgs $httpd $OPTIONS" >> $wdconfig
+        echo "TmpDir $wdtempdir" >> $wdconfig
+        echo "PidFile $wdpidfile" >> $wdconfig
+        chown pkiuser: $wdconfig
+ 
+        if [ -f /etc/init.d/functions ]; then
+            /usr/sbin/selinuxenabled
+            RETVAL=$?
+            if [ $RETVAL = 0 ] ; then
+                echo "ExeContext pki_tps_t" >> $wdconfig
+            fi
+            LANG=$HTTPD_LANG WDOG_NO_WATCH_SIGCHLD=1 /usr/bin/nuxwdog -f $wdconfig
+            echo -n $"Starting $prog:"
+        else
+            LANG=$HTTPD_LANG $httpd $OPTIONS -k start
+            echo -n $"Starting $prog:"
+        fi
 
 	RETVAL=$?
 	[ $RETVAL = 0 ] && touch ${lockfile}
@@ -624,6 +644,14 @@ start()
 stop()
 {
 	echo -n "Stopping $prog: "
+
+        #stop the watchdog daemon
+        if [ -f ${wdpidfile} ]; then
+            read kpid < ${wdpidfile}
+            kill -9 $kpid
+            rm -f ${wdpidfile}
+            rm -f ${wdtempdir}/nuxwdog.${kpid}
+        fi
 
 	if [ -f ${lockfile} ] ; then
 		$httpd $OPTIONS -k stop
