Copied PKI_8_BRANCH/pki to PKI_8_1_ERRATA_BRANCH.

diff --git a/pki/base/tps/apache/pki_instance_command_wrapper b/pki/base/tps/apache/pki_instance_command_wrapper
--- a/pki/base/tps/apache/pki_instance_command_wrapper
+++ b/pki/base/tps/apache/pki_instance_command_wrapper
@@ -26,6 +26,15 @@ if [ $? -ne 0 ] ; then
 	echo "Cannot invoke '$0' from non-existent directory!"
 	exit 255
 fi
+ 
+# Check to insure that at least one PKI subsystem
+# currently resides on this system.
+if	[ ! -x /usr/bin/pkiarch   ] ||
+	[ ! -x /usr/bin/pkiflavor ] ||
+	[ ! -x /usr/bin/pkiname   ]; then
+	echo "This machine is missing all PKI subsystems!"
+	exit 255
+fi
 
 
 ###############################################################################
@@ -75,11 +84,10 @@ invalid_architecture() {
 ##                                                                           ##
 ###############################################################################
 
-OS=`uname -s`
-ARCHITECTURE=""
+OS=`pkiname`
+ARCHITECTURE=`pkiarch`
 
 if [ "${OS}" = "Linux" ] ; then
-	ARCHITECTURE=`uname -i`
 	if [ "${ARCHITECTURE}" = "i386" ] ; then
 		LD_LIBRARY_PATH=/usr/lib/java:/usr/lib:/lib
 		LD_LIBRARY_PATH=/usr/lib/${PRODUCT}:${LD_LIBRARY_PATH}
@@ -118,11 +126,6 @@ if [ "${OS}" = "Linux" ] ; then
 		exit 255
 	fi
 elif [ "${OS}" = "SunOS" ] ; then
-	ARCHITECTURE=`uname -p`
-	if	[ "${ARCHITECTURE}" = "sparc" ] &&
-		[ -d "/usr/lib/sparcv9/" ] ; then
-		ARCHITECTURE="sparcv9"
-	fi
 	if [ "${ARCHITECTURE}" = "sparc" ] ; then
 		LD_LIBRARY_PATH=/usr/lib/java:/usr/lib:/lib
 		LD_LIBRARY_PATH=/usr/lib/${PRODUCT}:${LD_LIBRARY_PATH}
