Create PKI_8_0_ERRATA_BRANCH.

diff --git a/pki/base/tps/etc/init.d/httpd b/pki/base/tps/etc/init.d/httpd
--- a/pki/base/tps/etc/init.d/httpd
+++ b/pki/base/tps/etc/init.d/httpd
@@ -41,17 +41,26 @@ if [ $? -ne 0 ] ; then
 	exit 255
 fi
 
+# Check to insure that at least one PKI subsystem
+# currently resides on this system.
+if	[ ! -x /usr/bin/pkiarch   ] ||
+	[ ! -x /usr/bin/pkiflavor ] ||
+	[ ! -x /usr/bin/pkiname   ]; then
+	echo "This machine is missing all PKI subsystems!"
+	exit 255
+fi
+
 # Check to insure that this script's associated PKI
 # subsystem currently resides on this system.
 SUBSYSTEM_TYPE=[SUBSYSTEM_TYPE]
-if [ ! -d /usr/share/pki/${SUBSYSTEM_TYPE} ] ; then
+if [ ! -d /usr/share/`pkiflavor`/${SUBSYSTEM_TYPE} ] ; then
 	echo "This machine is missing the '${SUBSYSTEM_TYPE}' subsystem!"
 	exit 255
 fi
 
 # Obtain the operating system upon which this script is being executed
-OS=`uname -s`
-ARCHITECTURE=""
+OS=`pkiname`
+ARCHITECTURE=`pkiarch`
 
 # Time to wait in seconds, before killing process
 #
@@ -67,16 +76,10 @@ if [ ${OS} = "Linux" ] ; then
 		echo "Must be 'root' to execute '$0'!"
 		exit 1
 	fi
-	ARCHITECTURE=`uname -i`
 elif [ ${OS} = "SunOS" ] ; then
 	if [ `/usr/xpg4/bin/id -u` -ne 0 ] ; then
 		echo "Must be 'root' to execute '$0'!"
 		exit 1
-	fi
-	ARCHITECTURE=`uname -p`
-	if	[ "${ARCHITECTURE}" = "sparc" ] &&
-		[ -d "/usr/lib/sparcv9/" ] ; then
-		ARCHITECTURE="sparcv9"
 	fi
 else
 	echo "Unsupported OS '${OS}'!"
@@ -89,7 +92,7 @@ LD_LIBRARY_PATH=[SECURITY_LIBRARIES]:${LD_LIBRARY_PATH}
 export LD_LIBRARY_PATH
 
 # Source function library.
-if [ -f /etc/init.d/functions ]; then
+if [ -x /etc/init.d/functions ]; then
 	. /etc/init.d/functions
 else
 	# The checkpid() function is provided for platforms that do not
@@ -518,7 +521,7 @@ start()
 			if checkpid $kpid 2>&1; then
 				echo
 				echo "process already running"
-				return 255
+				return -1
 			else
 				echo
 				echo -n "lock file found but no process "
@@ -532,7 +535,7 @@ start()
         # restore context for ncipher hsm
         [ -x /sbin/restorecon ] && [ -d /dev/nfast ] && /sbin/restorecon -R /dev/nfast
 
-	if [ -f /etc/init.d/functions ]; then
+	if [ -x /etc/init.d/functions ]; then
 		/usr/sbin/selinuxenabled
 		RETVAL=$?
 		if [ $RETVAL = 0 ] ; then	
@@ -569,7 +572,7 @@ start()
 			let count=$count+1;
 		done
 
-		if [ -f /etc/init.d/functions ]; then
+		if [ -x /etc/init.d/functions ]; then
 			echo_success
 			echo
 		else
@@ -603,7 +606,7 @@ start()
 			done
 		fi
 	else
-		if [ -f /etc/init.d/functions ]; then
+		if [ -x /etc/init.d/functions ]; then
 			echo_failure
 			echo
 		else
@@ -653,14 +656,14 @@ stop()
 			rm -f ${lockfile}
 			rm -f ${pidfile}
 
-			if [ -f /etc/init.d/functions ]; then
+			if [ -x /etc/init.d/functions ]; then
 				echo_success
 				echo
 			else
 				echo "                                       [  OK  ]"
 			fi
 		else
-			if [ -f /etc/init.d/functions ]; then
+			if [ -x /etc/init.d/functions ]; then
 				echo_failure
 				echo
 			else
@@ -680,13 +683,13 @@ reload()
 	if ! LANG=$HTTPD_LANG $httpd $OPTIONS -t >&/dev/null; then
 		RETVAL=$?
 		echo $"not reloading due to configuration syntax error"
-		if [ -f /etc/init.d/functions ]; then
+		if [ -x /etc/init.d/functions ]; then
 			failure $"not reloading $httpd due to configuration syntax error"
 		else
 			echo $"not reloading $httpd due to configuration syntax error"
 		fi
 	else
-		if [ -f /etc/init.d/functions ]; then
+		if [ -x /etc/init.d/functions ]; then
 			killproc $httpd -HUP
 			# overwrite output from "killproc"
 			echo -n $"Stopping $prog:                                        "
