Errata tag for errata 9103

diff --git a/pki/base/tks/shared/etc/init.d/httpd b/pki/base/tks/shared/etc/init.d/httpd
--- a/pki/base/tks/shared/etc/init.d/httpd
+++ b/pki/base/tks/shared/etc/init.d/httpd
@@ -71,17 +71,25 @@ if [ $? -ne 0 ] ; then
 	exit 255
 fi
 
+# Check to insure that at least one PKI subsystem
+# currently resides on this system.
+if	[ ! -x /usr/bin/pkiarch   ] ||
+	[ ! -x /usr/bin/pkiflavor ] ||
+	[ ! -x /usr/bin/pkiname   ]; then
+	echo "This machine is missing all PKI subsystems!"
+	exit 255
+fi
+
 # Check to insure that this script's associated PKI
 # subsystem currently resides on this system.
 PKI_SUBSYSTEM_TYPE=[PKI_SUBSYSTEM_TYPE]
-if [ ! -d /usr/share/pki/${PKI_SUBSYSTEM_TYPE} ] ; then
+if [ ! -d /usr/share/`pkiflavor`/${PKI_SUBSYSTEM_TYPE} ] ; then
 	echo "This machine is missing the '${PKI_SUBSYSTEM_TYPE}' subsystem!"
 	exit 255
 fi
 
 # Obtain the operating system upon which this script is being executed
-OS=`uname -s`
-ARCHITECTURE=""
+OS=`pkiname`
 
 # This script must be run as root!
 RV=0
@@ -90,16 +98,10 @@ if [ ${OS} = "Linux" ] ; then
 		echo "Must be 'root' to execute '$0'!"
 		exit 1
 	fi
-	ARCHITECTURE=`uname -i`
 elif [ ${OS} = "SunOS" ] ; then
 	if [ `/usr/xpg4/bin/id -u` -ne 0 ] ; then
 		echo "Must be 'root' to execute '$0'!"
 		exit 1
-	fi
-	ARCHITECTURE=`uname -p`
-	if	[ "${ARCHITECTURE}" = "sparc" ] &&
-		[ -d "/usr/lib/sparcv9/" ] ; then
-		ARCHITECTURE="sparcv9"
 	fi
 else
 	echo "Unsupported OS '${OS}'!"
@@ -107,7 +109,7 @@ else
 fi
 
 # Source function library.
-if [ -f /etc/init.d/functions ]; then
+if [ -x /etc/init.d/functions ]; then
 	. /etc/init.d/functions
 else
 	# The checkpid() function is provided for platforms that do not
@@ -549,7 +551,7 @@ start()
 			if checkpid $kpid 2>&1; then
 				echo
 				echo "process already running"
-				return 255
+				return -1
 			else
 				echo
 				echo -n "lock file found but no process "
@@ -637,26 +639,26 @@ start()
 		CLASSPATH="$CLASSPATH":/usr/share/java/avalon-logkit.jar
 		CLASSPATH="$CLASSPATH":/usr/share/java/cmsutil.jar
 		CLASSPATH="$CLASSPATH":/usr/share/java/commons-logging.jar
-		if [ "$ARCHITECTURE" = "sparc" ] ; then
+		if [ `pkiarch` = "sparc" ] ; then
 			CLASSPATH="$CLASSPATH":/usr/lib/java/dirsec/jss4.jar
-		elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-			CLASSPATH="$CLASSPATH":/usr/lib/sparcv9/java/dirsec/jss4.jar
+		elif [ `pkiarch` = "sparcv9" ] ; then
+			CLASSPATH="$CLASSPATH":/usr/lib/`pkiarch`/java/dirsec/jss4.jar
 		fi
 		CLASSPATH="$CLASSPATH":/usr/share/java/ldapjdk.jar
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/common/lib/naming-factory.jar
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/common/lib/naming-resources.jar
-		CLASSPATH="$CLASSPATH":/usr/share/java/pki/nsutil.jar
-		if [ "$ARCHITECTURE" = "sparc" ] ; then
+		CLASSPATH="$CLASSPATH":/usr/share/java/`pkiflavor`/nsutil.jar
+		if [ `pkiarch` = "sparc" ] ; then
 			CLASSPATH="$CLASSPATH":/usr/lib/java/osutil.jar
-		elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-			CLASSPATH="$CLASSPATH":/usr/lib/sparcv9/java/osutil.jar
+		elif [ `pkiarch` = "sparcv9" ] ; then
+			CLASSPATH="$CLASSPATH":/usr/lib/`pkiarch`/java/osutil.jar
 		fi
 		CLASSPATH="$CLASSPATH":/usr/share/java/rhino.jar
 		CLASSPATH="$CLASSPATH":/usr/share/java/servletapi5.jar
-		if [ "$ARCHITECTURE" = "sparc" ] ; then
+		if [ `pkiarch` = "sparc" ] ; then
 			CLASSPATH="$CLASSPATH":/usr/lib/java/symkey.jar
-		elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-			CLASSPATH="$CLASSPATH":/usr/lib/sparcv9/java/symkey.jar
+		elif [ `pkiarch` = "sparcv9" ] ; then
+			CLASSPATH="$CLASSPATH":/usr/lib/`pkiarch`/java/symkey.jar
 		fi
 		CLASSPATH="$CLASSPATH":/usr/share/java/velocity.jar
 		CLASSPATH="$CLASSPATH":/usr/share/java/xalan-j2.jar
@@ -845,10 +847,10 @@ start()
 		### END LINUX-SPECIFIC FILE BUT SOLARIS-SPECIFIC LINK
 
 		### if [ ! -e /var/lib/tomcat5/common/lib/jss4.jar ]; then
-		###     if [ "$ARCHITECTURE" = "sparc" ] ; then
+		###     if [ `pkiarch` = "sparc" ] ; then
 		###         ln -s /usr/lib/java/dirsec/jss4.jar jss4.jar
-		###     elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-		###         ln -s /usr/lib/sparcv9/java/dirsec/jss4.jar jss4.jar
+		###     elif [ `pkiarch` = "sparcv9" ] ; then
+		###         ln -s /usr/lib/`pkiarch`/java/dirsec/jss4.jar jss4.jar
 		###     fi
 		### fi
 		### if [ ! -e /var/lib/tomcat5/common/lib/ldapjdk.jar ]; then
@@ -859,13 +861,13 @@ start()
 		### naming-resources.jar
 
 		### if [ ! -e /var/lib/tomcat5/common/lib/nsutil.jar ]; then
-		###     ln -s /usr/share/java/pki/nsutil.jar nsutil.jar
+		###     ln -s /usr/share/java/`pkiflavor`/nsutil.jar nsutil.jar
 		### fi
 		### if [ ! -e /var/lib/tomcat5/common/lib/osutil.jar ]; then
-		###     if [ "$ARCHITECTURE" = "sparc" ] ; then
+		###     if [ `pkiarch` = "sparc" ] ; then
 		###         ln -s /usr/lib/java/osutil.jar osutil.jar
-		###     elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-		###         ln -s /usr/lib/sparcv9/java/osutil.jar osutil.jar
+		###     elif [ `pkiarch` = "sparcv9" ] ; then
+		###         ln -s /usr/lib/`pkiarch`/java/osutil.jar osutil.jar
 		###     fi
 		### fi
 		### if [ ! -e /var/lib/tomcat5/common/lib/rhino.jar ]; then
@@ -879,10 +881,10 @@ start()
 		### END SOLARIS-SPECIFIC LINKS
 
 		### if [ ! -e /var/lib/tomcat5/common/lib/symkey.jar ]; then
-		###     if [ "$ARCHITECTURE" = "sparc" ] ; then
+		###     if [ `pkiarch` = "sparc" ] ; then
 		###         ln -s /usr/lib/java/symkey.jar symkey.jar
-		###     elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-		###         ln -s /usr/lib/sparcv9/java/symkey.jar symkey.jar
+		###     elif [ `pkiarch` = "sparcv9" ] ; then
+		###         ln -s /usr/lib/`pkiarch`/java/symkey.jar symkey.jar
 		###     fi
 		### fi
 		### if [ ! -e /var/lib/tomcat5/common/lib/velocity.jar ]; then
@@ -957,10 +959,10 @@ start()
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/server/lib/catalina-optional.jar
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/server/lib/catalina-storeconfig.jar
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/server/lib/catalina.jar
-		if [ "$ARCHITECTURE" = "sparc" ] ; then
+		if [ `pkiarch` = "sparc" ] ; then
 			CLASSPATH="$CLASSPATH":/usr/lib/java/dirsec/jss4.jar
-		elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-			CLASSPATH="$CLASSPATH":/usr/lib/sparcv9/java/dirsec/jss4.jar
+		elif [ `pkiarch` = "sparcv9" ] ; then
+			CLASSPATH="$CLASSPATH":/usr/lib/`pkiarch`/java/dirsec/jss4.jar
 		fi
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/server/lib/servlets-cgi.renametojar
 		CLASSPATH="$CLASSPATH":/var/lib/tomcat5/server/lib/servlets-default.jar
@@ -1020,10 +1022,10 @@ start()
 		### catalina-storeconfig.jar
 		### catalina.jar
 		### if [ ! -e /var/lib/tomcat5/server/lib/jss4.jar ]; then
-		###     if [ "$ARCHITECTURE" = "sparc" ] ; then
+		###     if [ `pkiarch` = "sparc" ] ; then
 		###         ln -s /usr/lib/java/dirsec/jss4.jar jss4.jar
-		###     elif [ "$ARCHITECTURE" = "sparcv9" ] ; then
-		###         ln -s /usr/lib/sparcv9/java/dirsec/jss4.jar jss4.jar
+		###     elif [ `pkiarch` = "sparcv9" ] ; then
+		###         ln -s /usr/lib/`pkiarch`/java/dirsec/jss4.jar jss4.jar
 		###     fi
 		### fi
 		### servlets-cgi.renametojar
@@ -1075,7 +1077,7 @@ start()
 			let count=$count+1;
 		done
 
-		if [ -f /etc/init.d/functions ]; then
+		if [ -x /etc/init.d/functions ]; then
 			if [ "$CONSOLETYPE" = "serial" ]; then
 				echo -n "         "
 			fi
@@ -1093,7 +1095,7 @@ start()
 		echo
 		status
 	else
-		if [ -f /etc/init.d/functions ]; then
+		if [ -x /etc/init.d/functions ]; then
 			if [ "$CONSOLETYPE" = "serial" ]; then
 				echo -n "         "
 			fi
@@ -1148,7 +1150,7 @@ stop()
 			rm -f ${lockfile}
 			rm -f ${pidfile}
 
-			if [ -f /etc/init.d/functions ]; then
+			if [ -x /etc/init.d/functions ]; then
 				if [ "$CONSOLETYPE" = "serial" ]; then
 					echo -n "         "
 				fi
@@ -1158,7 +1160,7 @@ stop()
 				echo "         [  OK  ]"
 			fi
 		else
-			if [ -f /etc/init.d/functions ]; then
+			if [ -x /etc/init.d/functions ]; then
 				if [ "$CONSOLETYPE" = "serial" ]; then
 					echo -n "         "
 				fi
